### PR TITLE
Fix crash in antighosting, fixes #88

### LINKED ISSUE #88: Crash in auto anti-ghosting
17efa5b8 master branch
1. Run LHDR through GDB,
2. New HDR Image
3. Add any images, tested using `flat_2015-12-04_karin_library_01_*.tif` and `img0*.jpg` from @fcomida 's [test pictures](https://github.com/LuminanceHDR/LuminanceHDR/issues/78#issuecomment-348821291).
4. Enable "Auto anti-ghosting"
5. Next, Finish, crash.

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 966240) >= this->size() (which is 966000)

Thread 25 "Thread (pooled)" received signal SIGABRT, Aborted.
[Switching to LWP 15518]
0x00007fffeaffd32b in raise () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007fffeaffd32b in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007fffeaffe9a1 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007fffebd8eb55 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
No symbol table info available.
#3  0x00007fffebd8bbf5 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
No symbol table info available.
#4  0x00007fffebd8a3c9 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
No symbol table info available.
#5  0x00007fffebd8b0f5 in __gxx_personality_v0 () from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
No symbol table info available.
#6  0x00007fffeb5a2f43 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libgcc_s.so.1
No symbol table info available.
#7  0x00007fffeb5a32cb in _Unwind_RaiseException () from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libgcc_s.so.1
No symbol table info available.
#8  0x00007fffebd8c07f in __cxa_throw () from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
No symbol table info available.
#9  0x00007fffebdbd8d1 in std::__throw_out_of_range_fmt(char const*, ...) () from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
No symbol table info available.
#10 0x0000555555850092 in std::vector<float, std::allocator<float> >::_M_range_check (this=0x7fff9c005a08, __n=966240) at /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/stl_vector.h:803
No locals.
#11 0x000055555584fcc5 in std::vector<float, std::allocator<float> >::at (this=0x7fff9c005a08, __n=966240) at /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/stl_vector.h:842
No locals.
#12 0x000055555584f36a in pfs::Array2D<float>::operator() (this=0x7fff9c005a00, cols=240, rows=805) at /home/morgan/programs/code-lhdr/src/Libpfs/array2d.hxx:93
No locals.
#13 0x000055555584d079 in blendGradients () at /home/morgan/programs/code-lhdr/src/HdrWizard/AutoAntighosting.cpp:516
        i = 240
        j = 804
        gradientXBlended = @0x7fff9c0039b0: {_vptr.Array2D = 0x555555e3f820 <vtable for pfs::Array2D<float>+16>, m_data = std::vector of length 966000, capacity 966000 = {0, 0.00273518264, 0.00904424489, 0.00544404984, 0.00632408261, 0.0105495751, -0.00195427239, 
            0.00378425419, 0.0115107447, 0.00853963196, 0.0176071227, 0.00483590364, 0.00467631221, -0.00162881613, 0.00134854019, 0.00909717381, 0.00969021022, 0.0071811527, -0.0019184351, 0.00394336134, 0.0073544085, 0.00230816752, 0.00675541162, 0.00749796629, 
            0.00191424787, 0.00745313615, 0.00387690216, 0.00573727489, 0.0132747889, 0.00751556456, 0.00579833984, 0.0264656544, 0.00699234009, 0.0119016171, -0.00981760025, 0.00813746452, 0.0197761059, -0.00415349007, 0.0016772747, 0.00671029091, 0.00381398201, 
            0.0109810829, 0.00171709061, -0.0156848431, -0.00089430809, 0.0156950951, 0.0799291134, 0.127820015, 0.0708096027, -0.00612688065, -0.0139191151, -0.0124492645, 0.000866651535, 0.0089006424, -0.0048866272, -0.00488495827, -0.0450136662, -0.0444025993, 
            -0.0393493176, -0.100039005, -0.0428612232, 0.0864245892, 0.106581211, 0.100697041, 0.0801706314, 0.123105049, 0.166806698, 0.0586178303, -0.104712725, -0.173486233, -0.0507240295, 0.139334917, 0.102136135, -0.097235918, -0.134645939, -0.0293426514, 
            0.0360639095, 0.0178668499, -0.00495481491, -0.01095891, 0.00295639038, 0.00639557838, 0.00501132011, 0.0105905533, -0.00468540192, -0.00103569031, 0.0153918266, 0.0128848553, 0.00842452049, -0.000677108765, -0.00199341774, -0.00413751602, -0.004956007, 
            0.00690960884, 0.00301551819, 0.0117783546, -0.000271081924, 0.0711033344, 0.271968365, 0.213176489, -0.137498617, -0.318630219, -0.149169445, 0.0336151123, 0.0639154911, 0.0133297443, 0.00704145432, 0.0458912849, 0.0195009708, 0.0206284523, 0.0246729851, 
            0.00475859642, -0.0219321251, -0.0488939285, -0.0308773518, 0.0208272934, -0.00511193275, -0.0089905262, 0.141911983, 0.105241776, -0.0901827812, -0.120807886, -0.026168108, 0.0336666107, -0.00507307053, -0.00485730171, 0.0157184601, 0.0128479004, 
            -0.00187182426, -0.0162112713, 0.0203235149, 0.021061182, 0.00154185295, -0.0217485428, -0.0467460155, -0.0476005077, 0.0139825344, -0.0432941914, -0.14598608, -0.0219860077, 0.109718084, 0.0532381535, -0.00512909889, 0.0103294849, -0.0151591301, 
            -0.0076084137, 0.0124120712, 0.0205698013, 0.010099411, 0.00279211998, 0.0345852375, 0.0428237915, 0.0178568363, 0.0251040459, 0.034794569, -0.0274996758, -0.129720688, -0.0240826607, -0.046833992, 0.0668685436, 0.220936775, 0.0344009399, 0.00333881378, 
            -0.00657868385, -0.0049841404, 0.0238082409, -0.00764393806, -0.0195508003, 0.0192716122, 0.0261757374, -0.0268087387, -0.0207855701, 0.0173687935, 0.0137064457, -0.0713236332, -0.154924631, -0.0200166702, -0.0198748112, 0.116387844, 0.185837984, 
            -0.0206990242, -0.0160427094, -0.0032787323, -0.00382137299, 0.00113272667, 0.015393734, 0.00419449806, -3.26633453e-05, 0.0142402649, -0.0138890743, -0.00402402878, 0.0224950314, -0.0324311256, -0.151344538, -0.0699646473, -0.0110216141, 0.11155653, 
            0.170683622, -0.0177075863, -0.0124628544...}, m_cols = 1200, m_rows = 805}
        gradientYBlended = @0x7fff9c0039f0: {_vptr.Array2D = 0x555555e3f820 <vtable for pfs::Array2D<float>+16>, m_data = std::vector of length 966000, capacity 966000 = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...}, 
          m_cols = 1200, m_rows = 805}
        gradientX = @0x7fff9c0058a0: {_vptr.Array2D = 0x555555e3f820 <vtable for pfs::Array2D<float>+16>, m_data = std::vector of length 966000, capacity 966000 = {0, 0.0132255554, 0.00313591957, 0.0101099014, 0.0160019398, -0.0150952339, 0.00552105904, 0.0206942558, 
            0.00857591629, 0.0305354595, 0.00475883484, 0.00585103035, -0.00369167328, -0.00160050392, 0.0101003647, 0.0144860744, 0.0139906406, -0.0100035667, 0.00121593475, 0.0142741203, 0.00163793564, 0.0103571415, 0.010119915, -0.00271272659, 0.00673913956, 
            0.00111293793, 0.00955820084, 0.0229487419, 0.010363102, -0.0191342831, 0.00579833984, 0.0264656544, 0.00699234009, 0.0119016171, -0.00981760025, 0.00813746452, 0.0197761059, -0.00415349007, 0.0016772747, 0.00671029091, 0.00381398201, 0.0109810829, 
            0.00171709061, -0.0156848431, -0.00089430809, 0.0156950951, 0.0799291134, 0.127820015, 0.0708096027, -0.00612688065, -0.0139191151, -0.0124492645, 0.000866651535, 0.0089006424, -0.0048866272, -0.00488495827, -0.0450136662, -0.0444025993, -0.0393493176, 
            -0.100039005, -0.0428612232, 0.0864245892, 0.106581211, 0.100697041, 0.0801706314, 0.123105049, 0.166806698, 0.0586178303, -0.104712725, -0.173486233, -0.0507240295, 0.139334917, 0.102136135, -0.097235918, -0.134645939, -0.0293426514, 0.0360639095, 
            0.0178668499, -0.00495481491, -0.01095891, 0.00295639038, 0.00639557838, 0.00501132011, 0.0105905533, -0.00468540192, -0.00103569031, 0.0153918266, 0.0128848553, 0.00842452049, -0.000677108765, -0.00199341774, -0.00413751602, -0.004956007, 0.00690960884, 
            0.00301551819, 0.0117783546, -0.000271081924, 0.0711033344, 0.271968365, 0.213176489, -0.137498617, -0.318630219, -0.149169445, 0.0336151123, 0.0639154911, 0.0133297443, 0.00704145432, 0.0458912849, 0.0195009708, 0.0206284523, 0.0246729851, 0.00475859642, 
            -0.0219321251, -0.0488939285, -0.0308773518, 0.0208272934, -0.00511193275, -0.0089905262, 0.141911983, 0.105241776, -0.0901827812, -0.120807886, -0.026168108, 0.0336666107, -0.00507307053, -0.00485730171, 0.0157184601, 0.0128479004, -0.00187182426, 
            -0.0162112713, 0.0203235149, 0.021061182, 0.00154185295, -0.0217485428, -0.0467460155, -0.0476005077, 0.0139825344, -0.0432941914, -0.14598608, -0.0219860077, 0.109718084, 0.0532381535, -0.00512909889, 0.0103294849, -0.0151591301, -0.0076084137, 
            0.0124120712, 0.0205698013, 0.010099411, 0.00279211998, 0.0345852375, 0.0428237915, 0.0178568363, 0.0251040459, 0.034794569, -0.0274996758, -0.129720688, -0.0240826607, -0.046833992, 0.0668685436, 0.220936775, 0.0344009399, 0.00333881378, -0.00657868385, 
            -0.0049841404, 0.0238082409, -0.00764393806, -0.0195508003, 0.0192716122, 0.0261757374, -0.0268087387, -0.0207855701, 0.0173687935, 0.0137064457, -0.0713236332, -0.154924631, -0.0200166702, -0.0198748112, 0.116387844, 0.185837984, -0.0206990242, 
            -0.0160427094, -0.0032787323, -0.00382137299, 0.00113272667, 0.015393734, 0.00419449806, -3.26633453e-05, 0.0142402649, -0.0138890743, -0.00402402878, 0.0224950314, -0.0324311256, -0.151344538, -0.0699646473, -0.0110216141, 0.11155653, 0.170683622, 
            -0.0177075863, -0.0124628544...}, m_cols = 1200, m_rows = 805}
        gradientY = @0x7fff9c003970: {_vptr.Array2D = 0x555555e3f820 <vtable for pfs::Array2D<float>+16>, m_data = std::vector of length 966000, capacity 966000 = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...}, m_cols = 1200, 
          m_rows = 805}
---Type <return> to continue, or q <return> to quit---
        gradientXGood = @0x7fff9c005a00: {_vptr.Array2D = 0x555555e3f820 <vtable for pfs::Array2D<float>+16>, m_data = std::vector of length 966000, capacity 966000 = {0, 0.007889539, 0.00547036529, 0.00486293435, 0.0077521801, 0.0025382638, 0.00509721041, 
            0.0111866891, 0.00204744935, 0.00232723355, 0.00850334764, 0.0046787858, 0.00491297245, 0.00350159407, 0.000434041023, 0.0042975843, 0.00809398293, 0.004894346, 0.000371664762, 0.00616669655, 0.00667078793, 0.000434696674, 0.0029783994, 0.00315368176, 
            0.00487601757, 0.00654122233, 0.00816713274, 0.0066408664, 0.00191634893, 0.0036008358, 0.00466802716, 0.003575176, 0.00385272503, 0.00610278547, 0.0061058253, 0.000626668334, 6.36279583e-05, 0.00384497643, -0.000139981508, 0.00340013206, 0.00442133844, 
            0.00187340379, 0.00213952363, 0.000363796949, 0.00273033977, 0.00496651232, 0.0371547788, 0.0683432668, 0.0450349599, 0.00768443942, -0.00328522176, -0.00340312719, -0.00160262734, -0.00197972357, -0.00835207105, -0.0114278346, -0.0202183276, -0.0218464881, 
            -0.0236653835, -0.0601967424, -0.0201318562, 0.0697041005, 0.0619219542, 0.0455787852, 0.0465134233, 0.0551356673, 0.0672520995, 0.0270136744, -0.0406331271, -0.0747732222, -0.0263502151, 0.0569181368, 0.0446462631, -0.0361911803, -0.0550734699, 
            -0.0127869844, 0.0166180432, 0.00597961992, -0.00410546362, 0.00278129429, 0.00333828479, -0.00268242508, 0.0023471266, 0.00462602824, 0.000421077013, 0.00104723126, 0.00307419151, 0.00400215387, 0.00244580209, 0.000145442784, 0.00217368454, 0.00269788504, 
            -0.00076213479, 0.00147332996, 0.00283040106, 0.0055840686, -0.000653214753, 0.0154204294, 0.0711394846, 0.0502791777, -0.0154356053, -0.0774562731, -0.0715735629, 0.0105952993, 0.0294863209, 0.0113918185, 0.00276122615, 0.013365265, 0.0215932876, 
            0.0107853636, 0.00625979714, 0.00396983884, -0.00724080019, -0.0163450409, -0.0117512494, 0.000563874841, -0.00558785349, -0.0077120848, 0.0514717512, 0.0508252494, -0.0322881453, -0.0466887914, -0.00585094094, 0.00834267586, 0.00101581961, 0.00228148699, 
            0.00165869296, -0.000286869705, 0.00140333548, 0.00507628173, 0.00269724056, 0.00145355426, 0.00397917628, -0.00893873535, -0.0227854662, -0.0141274482, 0.00360961258, -0.0234625973, -0.0560840666, -0.0127500668, 0.0420608781, 0.0225706324, -0.00445289537, 
            0.00213847309, 0.000986672938, 0.00208218023, 0.00666552037, 0.0042414628, 0.00290936604, 0.00792511553, 0.00892936438, 0.0155634247, 0.0199369211, 0.0109410994, 0.00738745369, -0.0118264519, -0.0648176447, -0.0139412247, -0.0227071792, 0.0442261584, 
            0.105746284, 0.00247079437, -0.0017707966, 0.00270884624, 0.0017707966, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.0292024743, -0.0623564571, -0.0151210036, -0.00437347591, 0.0443234779, 0.066729933, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.00467440765, -0.0528692938, 
            -0.0280497558, -0.000677015632, 0.0327241644, 0.0535463095, 0, 0...}, m_cols = 1200, m_rows = 805}
        gradientYGood = @0x7fff9c003930: {_vptr.Array2D = 0x555555e3f820 <vtable for pfs::Array2D<float>+16>, m_data = std::vector of length 966000, capacity 966000 = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...}, 
          m_cols = 1200, m_rows = 805}
        patches = 0x555556574c60
        gridX = 30
        gridY = 20
        width = 1200
        height = 805
        y = 40
        x = 8
```

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by gaaned92** [comment]
@heckflosse 
I cannot merge this PR with LuminanceHDR/master. You surely made other modifications in autoAntighosting.cpp.
I applied the  modif manually; there is no crash but output image has completely wrong colors.

**Comment by heckflosse** [comment]
@gaaned92 

> I cannot merge this PR with LuminanceHDR/master. You surely made other modifications in autoAntighosting.cpp.

No, I forked before @fcomida made a change to the code :(

I can post a patch that fits to master if you want to test

**Comment by gaaned92** [comment]
@heckflosse  yes please

**Comment by heckflosse** [comment]
@gaaned92 Here's the patch for Luminance hdr master branch:

```diff --git a/src/HdrWizard/AutoAntighosting.cpp b/src/HdrWizard/AutoAntighosting.cpp
index 960f93c6..d50e1ec9 100644
--- a/src/HdrWizard/AutoAntighosting.cpp
+++ b/src/HdrWizard/AutoAntighosting.cpp
@@ -500,7 +500,7 @@ void blendGradients(Array2Df &gradientXBlended, Array2Df &gradientYBlended,

     int x, y;
 //#pragma omp parallel for private(x, y) schedule(static)
-    for (int j = 0; j < height; j++) {
+    for (int j = 0; j < height - 1; j++) {
         y = floor(static_cast<float>(j) / gridY);
         for (int i = 0; i < width; i++) {
             x = floor(static_cast<float>(i) / gridX);

```

**Comment by gaaned92** [comment]
@heckflosse 
- the patch solves the crash but not the ugly output
- When are you going to submit PR for all your speed up so that they find their way in master branch?

**Comment by heckflosse** [comment]
@gaaned92 afaik @fcomida is already working on merging all the speedups.

**Comment by heckflosse** [comment]
Closing because it's also in #100

**Pull request closed without merging**
