### PR TITLE
Fix build with Qt 5.11.

### PR DESCRIPTION
**Pull request by krop**
qt5_use_modules was removed in Qt 5.11.

### CODE REVIEW

**Comment by krop** [comment]
Note: luminance-hdr-2.5.0-qtwebkit.patch wasn't refreshed because it can't be applied to the current master branch.

**Comment by heckflosse** [comment]
@krop I will have a look next days. Thanks for the pr :+1:

**Comment by krop** [comment]
I had to apply another patch to the 2.5.1 release for our openSUSE package:
https://build.opensuse.org/package/view_file/KDE:Extra/luminance-hdr/fix-build.patch
Explanation: if you explicitely want static libraries, mark them as such or it may be bypassed by some CMake options.
To get this, I ran:
`perl -i -p -e "s/ADD_LIBRARY\(([a-zA-Z-_]*)/ADD_LIBRARY\(\1 STATIC/g" src/**/CMakeLists.txt`
and added the missing 
`TARGET_LINK_LIBRARIES(helpbrowser Qt5::Core Qt5::Widgets Qt5::Xml Qt5::WebEngineWidgets)`
in src/helpbrowser/CMakeLists.txt.

Let me know if you want another PR for this fix.

**Comment by fcomida** [comment]
@krop @heckflosse I already pushed a fix in master for "qt5_uses_modules" since I was trying Qt5,11 on Fedora Rawhide. @krop I fixed the static libraries issue in building the Fedora RPM long ago by adding: -DBUILD_SHARED_LIBS:BOOL=OFF in the %build section of my SPEC file. Since OpenSUSE is RPM based I guess that option will work there too.

**Comment by krop** [comment]
our %cmake macro does the opposite, -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF. 
The only viable fix is to tell the build system the libraries have to be static regardless of the options, hence the need of the STATIC keyword.

**Comment by fcomida** [comment]
Fedora %cmake macro does the same. Adding -DBUILD_STATIC_LIBS:BOOL=OFF does work though.
...
%build
%{cmake} -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE=Release .
...

**Comment by krop** [comment]
I'm sorry to repeat it, but it's a build system issue in luminance. If the libraries have to be static for the project to build, the build system has to handle it.

**Comment by fcomida** [comment]
@krop ok I added STATIC to all sub-modules. Indeed it's the right way do do it. Many thanks. I guess I can close this.

**Comment by krop** [comment]
Thanks for pushing the fixes.

**Comment by heckflosse** [comment]
Still bilds fine on Windows/msys2 :+1:

**Comment by jluttine** [comment]
Is there a release coming up soon with this fix? Luminance HDR package is currently broken in one Linux distro because of this build error. Or should I just patch it somehow? I tried patching the latest release with this pull request but that didn't work probably because of other changes.

**Pull request closed without merging**
