### PR TITLE
Update of windowsInnoSetup.iss.in

### PR DESCRIPTION
**Pull request by gaaned92**
Permits to build with last MSYS2 dependencies update

### CODE REVIEW

**Comment by gaaned92** [comment]
@heckflosse @Hombre57 Could you test please?

**Comment by heckflosse** [comment]
@gaaned92 I will test as soon as I udated my MSYS2 environment. Still downloading...

**Comment by heckflosse** [comment]
@gaaned92 Though not related to your pr, I tried building lhdr in a freshly updated msys2 environment and get some errors:
```
CMake Error at C:/msys64/mingw64/share/cmake-3.12/Modules/FindBoost.cmake:2048 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: C:/msys64/mingw64/include

  Could not find the following static Boost libraries:

          boost_program_options
          boost_thread
          boost_chrono
          boost_system
          boost_date_time

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
```
Any idea?

**Comment by gaaned92** [comment]
@heckflosse I am still at boost version 1.68. aand I get no error.

**Comment by heckflosse** [comment]
@gaaned92 I downgraded to boost 1.68. No error now

**Pull request merged**
