### PR TITLE
handle plurals in translations

### PR DESCRIPTION
**Pull request by mikhirev**
Hi!
While working on Russian translation, I found a couple of strings with numbers that were not pluralized properly. I fixed them in code and updated *.ts files.

### CODE REVIEW

**Comment by danielkaneider** [comment]
Thanks

**Comment by mikhirev** [comment]
I see that you updated resource on Transifex, but I don't see these strings there. Moreover there are 2 untranslated English strings, but they are not displayed in interface. Is it TX bug?

**Comment by danielkaneider** [comment]
I noticed that, too. Might be a TX bug. I tried to contact them, let's see.

**Comment by danielkaneider** [comment]
I uploaded a new source file. Now the strings show up in the translations

**Pull request merged**
